version: "3.9"

services:
  clash:
    image: adoyle/clash-meta
    build:
      context: .
      dockerfile: ./meta.Dockerfile
    restart: unless-stopped
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml:ro
      # - ./ui:/ui:ro # dashboard volume
    ports:
      - "7890:7890"
      - "7891:7891"
      - "19090:9090" # The External Controller (RESTful API)
    network_mode: "bridge"

  dashboard:
    image: ghcr.io/metacubex/metacubexd
    restart: unless-stopped
    ports:
      - "19091:80"
    network_mode: "bridge"

  config_converter:
    image: tindy2013/subconverter:latest
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "19092:25500"
